[project]
name = "image-generation"
version = "0.1.0"
description = ""
authors = [
    {name = "yusongod0303",email = "yusongod33@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11, <3.14"
dependencies = [
    "diffusers (>=0.35.1,<0.36.0)",
    "transformers (>=4.56.2,<5.0.0)",
    "accelerate (>=1.10.1,<2.0.0)",
    "safetensors (>=0.6.2,<0.7.0)",
    "pillow (>=11.3.0,<12.0.0)",
    "fastapi (>=0.116.2,<0.117.0)",
    "uvicorn (>=0.36.0,<0.37.0)",
    "ollama (>=0.5.4,<0.6.0)"
]

[tool.poetry]
packages = [{include = "image_generation", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

